spring:
  ai:
    openai:
      #  API Key
      api-key: sk-ws-H.EHXRDII.DfGp.MEYCIQDa72mk6xzx38mFEBG-ez_hYsWrSEaD0NI5V88Y8RV3AAIhALSccEEtCofKQMRN3zv6QWe0q7e5KRGNwfsxnq0A4-hW
      #  Base URL?
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          # ???????????? qwen-turbo???? glm-4-flash
          model: qwen-turbo
      # 新增：配置 Embedding 模型
      embedding:
        options:
        # 通义千问兼容的 text-embedding 模型
          model: text-embedding-v1

# 自定义的 AI 提示词配置
my-ai:
  system-template: "你是一位{voice}语气的Java技术导师，回答问题要通俗易懂，多用比喻。"
  default-voice: "幽默风趣"
